CREATE DATABASE SE_db

USE SE_db

CREATE TABLE Usuarios(
idUsuario SMALLINT PRIMARY KEY IDENTITY,
NomeUsuario VARCHAR(30),
DDD CHAR(2),
Celular CHAR(9) NOT NULL,
Senha CHAR(60) NOT NULL
)
GO

CREATE TABLE TiposAnuncios(
idTipoAnuncio TINYINT PRIMARY KEY IDENTITY,
TipoAnuncio VARCHAR(18) NOT NULL UNIQUE
)
GO

CREATE TABLE Categorias(
idCategoria TINYINT PRIMARY KEY IDENTITY,
Categoria VARCHAR(30) NOT NULL UNIQUE
)
GO

CREATE TABLE Aprovacao(
idAprovacao TINYINT PRIMARY KEY IDENTITY,
Estado VARCHAR(12) UNIQUE
)
GO

CREATE TABLE Imoveis(
idImovel SMALLINT PRIMARY KEY IDENTITY,
idTipoAnuncio TINYINT FOREIGN KEY REFERENCES TiposAnuncios(idTipoAnuncio),
idCategoria TINYINT FOREIGN KEY REFERENCES Categorias(idCategoria),
idAprovacao TINYINT FOREIGN KEY REFERENCES Aprovacao(idAprovacao),
ImgPrincipal VARCHAR(41),
Titulo VARCHAR(100),
Descricao VARCHAR(400),
Bairro VARCHAR(30),
Aluguel	DECIMAL(7,2),
Valor DECIMAL(10,2),
CustosMensais DECIMAL(7,2),
Construido DECIMAL(7,2),
Terreno DECIMAL(7,2)
)
GO

CREATE TABLE dbImg(
idImg SMALLINT PRIMARY KEY IDENTITY,
idImovel SMALLINT FOREIGN KEY REFERENCES Imoveis(idImovel),
img VARCHAR(41)
)

CREATE TABLE TipoInfo(
idTipoInfo TINYINT PRIMARY KEY IDENTITY,
TipoInfo VARCHAR(25)
)
GO

CREATE TABLE InformacoesAdicionais(
idInfo SMALLINT PRIMARY KEY IDENTITY,
idTipoInfo TINYINT FOREIGN KEY REFERENCES TipoInfo(idTipoInfo),
idImovel SMALLINT FOREIGN KEY REFERENCES Imoveis(idImovel),
Quantidade TINYINT
)
GO